server:
  port : 8082

spring:
  profiles:
    active: @spring.profiles.active@

  datasource:
    continue-on-error: false
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password : @spring.datasource.password@
    driver-class-name: @spring.datasource.driver-class-name@

  jpa:
    #database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.auto: none

bezkoder:
    app:
      jwtSecret: bezKoderSecretKey
      jwtExpirationMs: 720




